/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author Fabián Espinoza
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lineaselect = new javax.swing.JComboBox<>();
        escogerRed = new javax.swing.JButton();
        t = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tselect = new javax.swing.JTextField();
        cambiart = new javax.swing.JButton();
        inicioParada = new javax.swing.JComboBox<>();
        MostrarGrafo = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineaselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caracas", "Bogota", "Otro" }));
        jPanel2.add(lineaselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 100, -1));

        escogerRed.setText("Escoger red");
        escogerRed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(escogerRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 40));

        t.setBackground(new java.awt.Color(0, 0, 0));
        t.setForeground(new java.awt.Color(0, 0, 0));
        t.setText("3");
        jPanel2.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("valor actual de t:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 100, -1));
        jPanel2.add(tselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        cambiart.setText("Seleccionar t");
        jPanel2.add(cambiart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 30));

        jPanel2.add(inicioParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        MostrarGrafo.setText("Mostrar Grafo");
        jPanel2.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton cambiart;
    private javax.swing.JButton escogerRed;
    private javax.swing.JComboBox<String> inicioParada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lineaselect;
    private javax.swing.JLabel t;
    private javax.swing.JTextField tselect;
    // End of variables declaration//GEN-END:variables


}
