/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyecto.pkg1.GrafoInterfaz;
import static proyecto.pkg1.GrafoInterfaz.*;
import proyecto.pkg1.Proyecto1;
import static proyecto.pkg1.Proyecto1.*;


/**
 *
 * @author Fabián Espinoza
 */
public class Ventana1 extends javax.swing.JFrame {
    public static File archivo;
    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        tactual.setText(t+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lineaselect = new javax.swing.JComboBox<>();
        escogerRed = new javax.swing.JButton();
        tactual = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tselect = new javax.swing.JTextField();
        cambiart = new javax.swing.JButton();
        inicioParada = new javax.swing.JComboBox<>();
        MostrarGrafo = new javax.swing.JButton();
        Nuevalinea = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineaselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caracas", "Bogota", "Otro" }));
        lineaselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaselectActionPerformed(evt);
            }
        });
        jPanel2.add(lineaselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 100, -1));

        escogerRed.setText("Escoger red");
        escogerRed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        escogerRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogerRedActionPerformed(evt);
            }
        });
        jPanel2.add(escogerRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 40));

        tactual.setBackground(new java.awt.Color(0, 0, 0));
        tactual.setText("3");
        jPanel2.add(tactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("valor actual de t:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 100, -1));

        tselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tselectActionPerformed(evt);
            }
        });
        jPanel2.add(tselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        cambiart.setText("Seleccionar t");
        cambiart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiartActionPerformed(evt);
            }
        });
        jPanel2.add(cambiart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 30));

        inicioParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioParadaActionPerformed(evt);
            }
        });
        jPanel2.add(inicioParada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        MostrarGrafo.setText("Mostrar Grafo");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        jPanel2.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 50));

        Nuevalinea.setText("nueva linea");
        Nuevalinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevalineaActionPerformed(evt);
            }
        });
        jPanel2.add(Nuevalinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiartActionPerformed
        
        try{
            t = Integer.parseInt(tselect.getText());
            if (t>=1) {
               tactual.setText(tselect.getText()); 
            }else{
                JOptionPane.showMessageDialog(null, "Error: Numero invalido\nTry again");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage()+ "\nTry again");
        }
        tselect.setText("");
    }//GEN-LAST:event_cambiartActionPerformed

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        String linea = lineaselect.getItemAt(lineaselect.getSelectedIndex());
        origen = inicioParada.getSelectedIndex();
        if (linea=="Caracas") {
          GrafoInterfaz.muestragrafo(t, Transporte);  
        }else if (linea=="Bogota") {
          GrafoInterfaz.muestragrafo(t, Transporte);  
        }else{
            if (miGrafo==null){
               JOptionPane.showMessageDialog(null, "Error\ninsertar un archivo compatible"); 
            }else{
                GrafoInterfaz.muestragrafo(t, Transporte);
            }
        }
        
    }//GEN-LAST:event_MostrarGrafoActionPerformed

    private void tselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tselectActionPerformed

    private void lineaselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineaselectActionPerformed

    private void escogerRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogerRedActionPerformed
        Proyecto1.FormateoGrafo();
        String linea = lineaselect.getItemAt(lineaselect.getSelectedIndex());
        
        if (linea=="Caracas") {
          miGrafo = extraerGrafo(caracas);
        }else if (linea=="Bogota") {
          miGrafo = extraerGrafo(bogota);
        }else{
            try{
        JFileChooser file=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto","json");
        file.setFileFilter(filter);
       
        file.showOpenDialog(file);
        archivo=file.getSelectedFile();
        int result = file.getDialogType();
        if (result == JFileChooser.APPROVE_OPTION) {
        miGrafo = extraerGrafo(archivo);
        }else{
             JOptionPane.showMessageDialog(null, "La carga de archivo se ha cancelado");
             
        }
            if (miGrafo==null) {
               JOptionPane.showMessageDialog(null, "Error");
            }
         
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error\ninsertar un archivo compatible");
        }
        }
        inicioParada.removeAllItems();
        for (int i = 0; i < miGrafo.getUsuarios().length; i++) {
            String nombre = miGrafo.getUsuarios()[i].getNickname();
            inicioParada.addItem(nombre);
            
        }
    }//GEN-LAST:event_escogerRedActionPerformed

    private void inicioParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioParadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioParadaActionPerformed

    private void NuevalineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevalineaActionPerformed
        
            try{
        JFileChooser file=new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto","json");
        file.setFileFilter(filter);
       
        file.showOpenDialog(file);
        archivo=file.getSelectedFile();
        int result = file.getDialogType();
        if (result == JFileChooser.APPROVE_OPTION) {
        miGrafo = agregarlinea(archivo);
        }else{
             JOptionPane.showMessageDialog(null, "La carga de archivo se ha cancelado");
             
        }
            if (miGrafo==null) {
               JOptionPane.showMessageDialog(null, "Error");
            }
         inicioParada.removeAllItems();
        for (int i = 0; i < miGrafo.getUsuarios().length; i++) {
            String nombre = miGrafo.getUsuarios()[i].getNickname();
            inicioParada.addItem(nombre);
            
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error\ninsertar un archivo compatible");
        }
    }//GEN-LAST:event_NuevalineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Proyecto1.FormateoGrafo();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton Nuevalinea;
    private javax.swing.JButton cambiart;
    private javax.swing.JButton escogerRed;
    private javax.swing.JComboBox<String> inicioParada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lineaselect;
    private javax.swing.JLabel tactual;
    private javax.swing.JTextField tselect;
    // End of variables declaration//GEN-END:variables


}
